// ============================================================
//  GOVERNMENT JOBS DATA
// ============================================================
const JOBS = [
  {
    id: "j1",
    title: "Junior Engineer (Civil)",
    org: "Public Works Department, Uttar Pradesh",
    sector: "Engineering",
    state: "Uttar Pradesh",
    qualification: "B.E / B.Tech",
    vacancies: 3500,
    salary: "₹35,400 – ₹1,12,400 per month",
    age: "21 – 40 years",
    lastDate: "2025-03-15",
    status: "open",
    type: "State",
    description: "UP PWD invites applications for Junior Engineer (Civil) posts. Candidates with a B.E/B.Tech in Civil Engineering from a recognized university may apply online through the official portal.",
    link: "https://uppsc.up.nic.in",
    requirements: ["B.E/B.Tech in Civil Engineering", "Registered with UP State Engineers Board", "Proficiency in AutoCAD preferred"],
    selectionProcess: "Written Exam → Document Verification → Medical Test"
  },
  {
    id: "j2",
    title: "Staff Selection Commission – CHSL (10+2)",
    org: "Staff Selection Commission, Central Govt",
    sector: "Clerical / Administrative",
    state: "All India",
    qualification: "12th Pass",
    vacancies: 3712,
    salary: "₹19,900 – ₹63,200 per month",
    age: "18 – 27 years",
    lastDate: "2025-04-10",
    status: "open",
    type: "Central",
    description: "SSC CHSL recruits Lower Division Clerks (LDC), Data Entry Operators (DEO), Postal/Sorting Assistants across Central Government Ministries & Departments.",
    link: "https://ssc.nic.in",
    requirements: ["12th Pass from recognised board", "Basic typing speed (35 wpm English / 30 wpm Hindi)", "Indian Citizen"],
    selectionProcess: "Tier-I CBT → Tier-II (Descriptive) → Typing Test → Document Verification"
  },
  {
    id: "j3",
    title: "Constable (GD) CAPF",
    org: "SSC – BSF, CISF, CRPF, SSB, ITBP, AR",
    sector: "Defence / Police",
    state: "All India",
    qualification: "10th Pass",
    vacancies: 39481,
    salary: "₹21,700 – ₹69,100 per month",
    age: "18 – 23 years",
    lastDate: "2025-02-28",
    status: "closed",
    type: "Central",
    description: "SSC GD Constable recruitment for Central Armed Police Forces including BSF, CISF, CRPF, SSB, ITBP, and Assam Rifles.",
    link: "https://ssc.nic.in",
    requirements: ["10th pass from recognised board", "Minimum height 170 cm (Male) / 157 cm (Female)", "Physical fitness"],
    selectionProcess: "CBT → PET/PST → Medical Examination → Document Verification"
  },
  {
    id: "j4",
    title: "IBPS PO (Probationary Officer)",
    org: "Institute of Banking Personnel Selection",
    sector: "Banking",
    state: "All India",
    qualification: "Graduation",
    vacancies: 4455,
    salary: "₹36,000 – ₹63,840 per month",
    age: "20 – 30 years",
    lastDate: "2025-08-20",
    status: "soon",
    type: "Central",
    description: "IBPS CRP PO/MT recruitment for Public Sector Banks. Successful candidates are placed as Probationary Officers in participating banks across the country.",
    link: "https://ibps.in",
    requirements: ["Graduation in any discipline", "Knowledge of computer operations", "Valid IBPS score card"],
    selectionProcess: "Prelims → Mains → Interview → Document Verification"
  },
  {
    id: "j5",
    title: "Teacher (TGT/PGT)",
    org: "Navodaya Vidyalaya Samiti, MoE",
    sector: "Education",
    state: "All India",
    qualification: "Post Graduation + B.Ed",
    vacancies: 1377,
    salary: "₹47,600 – ₹1,51,100 per month",
    age: "21 – 40 years",
    lastDate: "2025-05-30",
    status: "open",
    type: "Central",
    description: "NVS recruits Trained Graduate Teachers (TGT) and Post Graduate Teachers (PGT) for Jawahar Navodaya Vidyalayas across India.",
    link: "https://navodaya.gov.in",
    requirements: ["Post Graduation in relevant subject", "B.Ed from NCTE recognised institution", "CTET/NVS TGT Paper qualification"],
    selectionProcess: "Written Test → Interview"
  },
  {
    id: "j6",
    title: "Assistant Commandant",
    org: "Central Reserve Police Force (CRPF)",
    sector: "Defence / Police",
    state: "All India",
    qualification: "Graduation",
    vacancies: 212,
    salary: "₹56,100 – ₹1,77,500 per month",
    age: "20 – 25 years",
    lastDate: "2025-03-31",
    status: "open",
    type: "Central",
    description: "CRPF invites applications for Group 'A' (Gazetted) post of Assistant Commandant in General Duty category through UPSC examination.",
    link: "https://crpf.gov.in",
    requirements: ["Bachelor's Degree", "Physical fitness standards", "Indian Citizen"],
    selectionProcess: "UPSC Written Exam → Physical Test → Interview → Medical"
  },
  {
    id: "j7",
    title: "Revenue Inspector",
    org: "Revenue Department, Maharashtra",
    sector: "Revenue / Administration",
    state: "Maharashtra",
    qualification: "Graduation",
    vacancies: 826,
    salary: "₹28,900 – ₹91,300 per month",
    age: "18 – 38 years",
    lastDate: "2025-04-25",
    status: "open",
    type: "State",
    description: "MPSC invites applications for Revenue Inspector posts under the Maharashtra Revenue Department.",
    link: "https://mpsc.gov.in",
    requirements: ["Bachelor's Degree", "Marathi language proficiency", "Knowledge of local revenue laws"],
    selectionProcess: "Prelims → Mains → Document Verification"
  },
  {
    id: "j8",
    title: "Sub Inspector of Police",
    org: "Rajasthan Police, Home Department",
    sector: "Police",
    state: "Rajasthan",
    qualification: "Graduation",
    vacancies: 859,
    salary: "₹33,800 – ₹1,07,000 per month",
    age: "20 – 25 years",
    lastDate: "2025-06-15",
    status: "soon",
    type: "State",
    description: "Rajasthan Police SI recruitment for the post of Sub Inspector (GD/CID/Intelligence) across Rajasthan.",
    link: "https://police.rajasthan.gov.in",
    requirements: ["Graduation", "Physical standards met", "No criminal record"],
    selectionProcess: "Written Exam → PET/PST → Medical → Interview"
  },
  {
    id: "j9",
    title: "DRDO Scientist 'B'",
    org: "Defence Research & Development Organisation",
    sector: "Science & Technology",
    state: "All India",
    qualification: "B.E / B.Tech",
    vacancies: 1007,
    salary: "₹56,100 – ₹1,77,500 per month",
    age: "28 years (max)",
    lastDate: "2025-07-31",
    status: "open",
    type: "Central",
    description: "DRDO CEPTAM recruits Scientists 'B' in various engineering/science disciplines for defence R&D laboratories.",
    link: "https://drdo.gov.in",
    requirements: ["B.E/B.Tech or M.Sc in relevant discipline", "First class or equivalent", "GATE score preferred"],
    selectionProcess: "Tier-I (DRDO CEPTAM Exam) → Tier-II (Personal Interview)"
  },
  {
    id: "j10",
    title: "Forest Guard",
    org: "Forest Department, Madhya Pradesh",
    sector: "Forest & Environment",
    state: "Madhya Pradesh",
    qualification: "12th Pass",
    vacancies: 1540,
    salary: "₹19,500 – ₹62,000 per month",
    age: "18 – 33 years",
    lastDate: "2025-05-10",
    status: "open",
    type: "State",
    description: "MP Forest Department recruits Forest Guards for protection and management of forest areas in Madhya Pradesh.",
    link: "https://forest.mp.gov.in",
    requirements: ["12th Pass", "Physical fitness", "Resident of MP preferred"],
    selectionProcess: "Written Exam → Physical Efficiency Test → Medical"
  },
  {
    id: "j11",
    title: "LIC AAO (Assistant Administrative Officer)",
    org: "Life Insurance Corporation of India",
    sector: "Insurance",
    state: "All India",
    qualification: "Graduation",
    vacancies: 300,
    salary: "₹53,600 – ₹95,100 per month",
    age: "21 – 30 years",
    lastDate: "2025-09-05",
    status: "soon",
    type: "Central",
    description: "LIC AAO recruitment for Assistant Administrative Officers in various specialisations including IT, Chartered Accountant, Actuarial, and Generalist.",
    link: "https://licindia.in",
    requirements: ["Bachelor's Degree", "CA / Actuarial / IT stream eligibility varies", "Indian Citizen"],
    selectionProcess: "Prelims → Mains → Interview → Document Verification"
  },
  {
    id: "j12",
    title: "Assistant Loco Pilot (ALP)",
    org: "Railway Recruitment Board (RRB)",
    sector: "Railways",
    state: "All India",
    qualification: "10th + ITI / Diploma",
    vacancies: 5696,
    salary: "₹19,900 – ₹66,800 per month",
    age: "18 – 28 years",
    lastDate: "2025-04-30",
    status: "open",
    type: "Central",
    description: "RRB ALP recruitment under Railway Recruitment Boards for the post of Assistant Loco Pilot across Indian Railways zones.",
    link: "https://rrbcdg.gov.in",
    requirements: ["Matriculation + ITI or Diploma in relevant trade", "Valid ITI from NCVT/SCVT"],
    selectionProcess: "CBT Stage-1 → CBT Stage-2 → CBAT → Document Verification → Medical"
  }
];

// ============================================================
//  GOVERNMENT SCHEMES DATA
// ============================================================
const SCHEMES = [
  {
    id: "s1",
    name: "Pradhan Mantri Jan Dhan Yojana (PMJDY)",
    ministry: "Ministry of Finance",
    category: "Financial",
    beneficiary: "All Citizens",
    type: "Central",
    icon: "🏦",
    status: "active",
    benefit: "Zero-balance bank account with RuPay debit card, ₹2 lakh accident insurance, ₹30,000 life cover, and overdraft facility up to ₹10,000.",
    description: "PMJDY is a national mission for financial inclusion to ensure access to financial services such as savings accounts, remittance, credit, insurance and pension at affordable cost. Over 50 crore accounts opened.",
    eligibility: "Any Indian resident above 10 years of age who does not have a bank account.",
    howToApply: "Visit nearest bank branch or BC outlet with Aadhaar/official valid document.",
    link: "https://pmjdy.gov.in",
    launchedYear: "2014"
  },
  {
    id: "s2",
    name: "PM Kisan Samman Nidhi (PM-KISAN)",
    ministry: "Ministry of Agriculture & Farmers Welfare",
    category: "Agriculture",
    beneficiary: "Farmers",
    type: "Central",
    icon: "🌾",
    status: "active",
    benefit: "Direct income support of ₹6,000 per year in three equal instalments of ₹2,000 directly into farmers' bank accounts.",
    description: "PM-KISAN provides income support to all landholding farmers' families to supplement their financial needs. Over 11 crore beneficiaries receive direct benefit transfer.",
    eligibility: "Farmer families with cultivable landholding. Small & marginal farmers prioritised.",
    howToApply: "Register through PM-KISAN portal or at nearest Common Service Centre (CSC).",
    link: "https://pmkisan.gov.in",
    launchedYear: "2019"
  },
  {
    id: "s3",
    name: "Pradhan Mantri Awas Yojana (PMAY)",
    ministry: "Ministry of Housing & Urban Affairs",
    category: "Housing",
    beneficiary: "EWS / LIG / MIG",
    type: "Central",
    icon: "🏠",
    status: "active",
    benefit: "Subsidy on home loans up to ₹2.67 lakh for EWS, ₹2.35 lakh for LIG, and up to ₹2.30 lakh for MIG categories.",
    description: "PMAY aims to provide affordable housing to urban poor by 2024. The Credit Linked Subsidy Scheme (CLSS) offers interest subsidy on home loans to eligible beneficiaries.",
    eligibility: "EWS (income < ₹3L), LIG (₹3–6L), MIG-I (₹6–12L), MIG-II (₹12–18L) annual income.",
    howToApply: "Apply through empanelled banks, HFCs, or Common Service Centres.",
    link: "https://pmaymis.gov.in",
    launchedYear: "2015"
  },
  {
    id: "s4",
    name: "Ayushman Bharat – PM-JAY",
    ministry: "Ministry of Health & Family Welfare",
    category: "Health",
    beneficiary: "Below Poverty Line Families",
    type: "Central",
    icon: "🏥",
    status: "active",
    benefit: "Health coverage up to ₹5 lakh per family per year for secondary and tertiary care hospitalisation at empanelled public and private hospitals.",
    description: "Ayushman Bharat PM-JAY is the world's largest government-funded health assurance scheme, covering over 12 crore poor and vulnerable families.",
    eligibility: "Families identified based on SECC 2011 data. No premium required from beneficiary.",
    howToApply: "Check eligibility at mera.pmjay.gov.in. Get Golden Card at CSC or empanelled hospital.",
    link: "https://pmjay.gov.in",
    launchedYear: "2018"
  },
  {
    id: "s5",
    name: "PM Ujjwala Yojana (PMUY)",
    ministry: "Ministry of Petroleum & Natural Gas",
    category: "Welfare",
    beneficiary: "Women (BPL)",
    type: "Central",
    icon: "🔥",
    status: "active",
    benefit: "Free LPG connection including security deposit waiver, first cylinder and pressure regulator. Refills available at subsidised rates.",
    description: "PMUY provides clean cooking fuel to women from BPL households, replacing polluting chulhas and improving health outcomes for rural women.",
    eligibility: "Adult women from BPL households not having existing LPG connection.",
    howToApply: "Visit nearest LPG distributor with BPL card and Aadhaar.",
    link: "https://pmuy.gov.in",
    launchedYear: "2016"
  },
  {
    id: "s6",
    name: "National Scholarship Portal (NSP)",
    ministry: "Ministry of Education",
    category: "Education",
    beneficiary: "Students",
    type: "Central",
    icon: "📚",
    status: "active",
    benefit: "Merit-cum-means scholarships ranging from ₹2,000 to ₹20,000 per year for pre-matric, post-matric and merit-based categories.",
    description: "NSP is a one-stop platform offering 50+ scholarship schemes from Central, State governments and UGC/AICTE for students from SC/ST/OBC/Minorities/EWS and meritorious backgrounds.",
    eligibility: "Indian students enrolled in recognised institutions. Income, merit, and category-specific eligibility applies.",
    howToApply: "Register and apply online at scholarships.gov.in during open application window.",
    link: "https://scholarships.gov.in",
    launchedYear: "2015"
  },
  {
    id: "s7",
    name: "Pradhan Mantri Mudra Yojana (PMMY)",
    ministry: "Ministry of Finance",
    category: "Employment",
    beneficiary: "Small Entrepreneurs",
    type: "Central",
    icon: "💼",
    status: "active",
    benefit: "Collateral-free business loans: Shishu (up to ₹50,000), Kishore (₹50,000–₹5L), Tarun (₹5L–₹10L). Tarun Plus up to ₹20L for repeat borrowers.",
    description: "PMMY provides micro-credit to non-corporate, non-farm small/micro enterprises through member lending institutions (MLIs) to boost self-employment.",
    eligibility: "Any Indian citizen with a business plan for income-generating activity in manufacturing, processing, trading or service sector.",
    howToApply: "Apply at any bank, MFI, or NBFC. Use Mudra Portal or visit nearest branch.",
    link: "https://mudra.org.in",
    launchedYear: "2015"
  },
  {
    id: "s8",
    name: "Sukanya Samriddhi Yojana (SSY)",
    ministry: "Ministry of Finance (India Post)",
    category: "Financial",
    beneficiary: "Girl Child",
    type: "Central",
    icon: "👧",
    status: "active",
    benefit: "8.2% p.a. interest (tax-free), Section 80C deduction up to ₹1.5L per year, maturity corpus after 21 years.",
    description: "SSY is a small savings scheme for the girl child under Beti Bachao Beti Padhao. Account can be opened for girls below 10 years at post offices and authorised banks.",
    eligibility: "Parents/guardians of a girl child below 10 years of age. Max. 2 accounts per family.",
    howToApply: "Visit any post office or authorised bank with birth certificate and guardian's KYC documents.",
    link: "https://www.indiapost.gov.in",
    launchedYear: "2015"
  },
  {
    id: "s9",
    name: "PM Vishwakarma Yojana",
    ministry: "Ministry of MSME",
    category: "Employment",
    beneficiary: "Artisans / Craftsmen",
    type: "Central",
    icon: "🔨",
    status: "active",
    benefit: "₹15,000 toolkit incentive, skill training with ₹500/day stipend, collateral-free credit up to ₹3 lakh at 5% concessional rate, and digital transaction incentives.",
    description: "PM Vishwakarma supports traditional artisans and craftsmen across 18 trades (Lohars, Kumbhars, Darzi, Mochis, etc.) to improve quality, scale, and income.",
    eligibility: "Artisans/craftsmen engaged in 18 specified traditional trades. Registered on PM Vishwakarma portal.",
    howToApply: "Self-register at pmvishwakarma.gov.in through CSC or mobile app.",
    link: "https://pmvishwakarma.gov.in",
    launchedYear: "2023"
  },
  {
    id: "s10",
    name: "Atal Pension Yojana (APY)",
    ministry: "Ministry of Finance (PFRDA)",
    category: "Financial",
    beneficiary: "Unorganised Sector Workers",
    type: "Central",
    icon: "👴",
    status: "active",
    benefit: "Guaranteed pension of ₹1,000–₹5,000 per month after age 60. Spouse continues pension on subscriber's death. Nominee receives corpus on spouse's death.",
    description: "APY provides old-age income security to workers in the unorganised sector. Central Government co-contributes 50% of total contribution (up to ₹1,000/year) for 5 years.",
    eligibility: "Indian citizens aged 18–40 with savings bank account. Not an income tax payer.",
    howToApply: "Contact your bank or apply through net banking/mobile banking.",
    link: "https://npscra.nsdl.co.in/scheme-details.php",
    launchedYear: "2015"
  },
  {
    id: "s11",
    name: "Beti Bachao Beti Padhao (BBBP)",
    ministry: "Ministry of Women & Child Development",
    category: "Women",
    beneficiary: "Girl Child / Women",
    type: "Central",
    icon: "👩‍🎓",
    status: "active",
    benefit: "Multi-sectoral interventions: education grants, conditional cash transfers, awareness campaigns, legal aid, and Sukanya Samriddhi Account linkage.",
    description: "BBBP addresses declining Child Sex Ratio (CSR) and related issues of empowerment of women over a life-cycle continuum through advocacy, communication and convergence.",
    eligibility: "Primarily targets districts with low Child Sex Ratio. Benefits flow to girl children and women generally.",
    howToApply: "Benefits delivered through ICDS, school, and health system. Contact Anganwadi centre or district WCD office.",
    link: "https://wcd.nic.in",
    launchedYear: "2015"
  },
  {
    id: "s12",
    name: "Digital India Land Records Modernisation",
    ministry: "Ministry of Rural Development",
    category: "Welfare",
    beneficiary: "Land Owners / Farmers",
    type: "Central",
    icon: "🗺️",
    status: "active",
    benefit: "Computerised Record of Rights (RoR), online mutation, linkage of registration & mutation, unique land parcel ID (ULPIN/Bhu-Aadhaar).",
    description: "The programme aims to provide real-time land record services to all citizens, reduce land disputes, lower transaction costs and bring greater transparency.",
    eligibility: "All land owners and residents in participating states/UTs.",
    howToApply: "Access state land record portals (e.g., Bhulekh, Bhoomi, Dharani) or visit sub-registrar office.",
    link: "https://dolr.gov.in",
    launchedYear: "2008"
  }
];

// ============================================================
//  ALL INDIAN STATES & UTs (for dropdown)
// ============================================================
const ALL_STATES = [
  "All India",
  // States
  "Andhra Pradesh", "Arunachal Pradesh", "Assam", "Bihar", "Chhattisgarh",
  "Goa", "Gujarat", "Haryana", "Himachal Pradesh", "Jharkhand",
  "Karnataka", "Kerala", "Madhya Pradesh", "Maharashtra", "Manipur",
  "Meghalaya", "Mizoram", "Nagaland", "Odisha", "Punjab",
  "Rajasthan", "Sikkim", "Tamil Nadu", "Telangana", "Tripura",
  "Uttar Pradesh", "Uttarakhand", "West Bengal",
  // Union Territories
  "Andaman & Nicobar Islands", "Chandigarh", "Dadra & Nagar Haveli and Daman & Diu",
  "Delhi", "Jammu & Kashmir", "Ladakh", "Lakshadweep", "Puducherry"
];

// ============================================================
//  EXTRA JOBS (one per uncovered state)
// ============================================================
const EXTRA_JOBS = [
  {
    id: "j13",
    title: "Police Constable (GD)",
    org: "Andhra Pradesh Police Department",
    sector: "Police",
    state: "Andhra Pradesh",
    qualification: "12th Pass",
    vacancies: 6100,
    salary: "₹21,230 – ₹63,010 per month",
    age: "18 – 25 years",
    lastDate: "2025-06-30",
    status: "open",
    type: "State",
    description: "APSLPRB recruits Police Constable (General) for Civil Police, AR, SAR CPL under AP Home Dept.",
    link: "https://slprb.ap.gov.in",
    requirements: ["12th Pass", "Physical standards", "Resident of AP"],
    selectionProcess: "Written Exam → PET/PMT → Medical"
  },
  {
    id: "j14",
    title: "Junior Secretariat Assistant",
    org: "Arunachal Pradesh PSC",
    sector: "Clerical / Administrative",
    state: "Arunachal Pradesh",
    qualification: "12th Pass",
    vacancies: 218,
    salary: "₹19,900 – ₹63,200 per month",
    age: "18 – 32 years",
    lastDate: "2025-07-15",
    status: "open",
    type: "State",
    description: "APPSC recruits Junior Secretariat Assistants for various departments of the Arunachal Pradesh Government.",
    link: "https://appsc.gov.in",
    requirements: ["12th Pass", "Basic computer knowledge", "Typing proficiency"],
    selectionProcess: "Written Test → Typing Test → Document Verification"
  },
  {
    id: "j15",
    title: "Junior Engineer (Electrical)",
    org: "Assam Power Distribution Company Ltd",
    sector: "Engineering",
    state: "Assam",
    qualification: "Diploma / B.E",
    vacancies: 412,
    salary: "₹28,700 – ₹91,900 per month",
    age: "18 – 38 years",
    lastDate: "2025-05-20",
    status: "open",
    type: "State",
    description: "APDCL recruits Junior Engineers in Electrical discipline for power distribution across Assam.",
    link: "https://apdcl.org",
    requirements: ["Diploma or B.E in Electrical Engineering", "Assam domicile preferred"],
    selectionProcess: "Written Test → Interview"
  },
  {
    id: "j16",
    title: "Bihar Police SI (Sub-Inspector)",
    org: "Bihar Police, Home Department",
    sector: "Police",
    state: "Bihar",
    qualification: "Graduation",
    vacancies: 1275,
    salary: "₹35,400 – ₹1,12,400 per month",
    age: "20 – 37 years",
    lastDate: "2025-08-10",
    status: "soon",
    type: "State",
    description: "BPSSC recruits Sub-Inspectors for Bihar Police under competitive written examination.",
    link: "https://bpssc.bih.nic.in",
    requirements: ["Graduation", "Physical fitness", "Bihar domicile"],
    selectionProcess: "Prelims → Mains → PET/PMT → Medical"
  },
  {
    id: "j17",
    title: "Patwari / Revenue Inspector",
    org: "Chhattisgarh Vyapam",
    sector: "Revenue / Administration",
    state: "Chhattisgarh",
    qualification: "12th Pass",
    vacancies: 593,
    salary: "₹19,500 – ₹62,000 per month",
    age: "18 – 35 years",
    lastDate: "2025-04-05",
    status: "open",
    type: "State",
    description: "CGVYAPAM recruits Patwaris for revenue management and land record maintenance in Chhattisgarh.",
    link: "https://vyapam.cgstate.gov.in",
    requirements: ["12th Pass with computer certificate", "CG domicile", "Hindi proficiency"],
    selectionProcess: "Written Exam → Document Verification"
  },
  {
    id: "j18",
    title: "Goa PSC – Assistant Section Officer",
    org: "Goa Public Service Commission",
    sector: "Clerical / Administrative",
    state: "Goa",
    qualification: "Graduation",
    vacancies: 84,
    salary: "₹28,900 – ₹91,300 per month",
    age: "18 – 45 years",
    lastDate: "2025-09-25",
    status: "soon",
    type: "State",
    description: "Goa PSC recruits Assistant Section Officers for various state government departments.",
    link: "https://gpsc.goa.gov.in",
    requirements: ["Graduation in any discipline", "Konkani language knowledge", "Computer literacy"],
    selectionProcess: "Written Exam → Interview"
  },
  {
    id: "j19",
    title: "GPSC Class-I/II Officer",
    org: "Gujarat Public Service Commission",
    sector: "Civil Services",
    state: "Gujarat",
    qualification: "Graduation",
    vacancies: 436,
    salary: "₹53,100 – ₹1,67,800 per month",
    age: "21 – 35 years",
    lastDate: "2025-06-05",
    status: "open",
    type: "State",
    description: "GPSC conducts Combined State Services examination to recruit Class-I and Class-II officers for the Gujarat Government.",
    link: "https://gpsc.gujarat.gov.in",
    requirements: ["Graduation", "Gujarati language proficiency", "Gujarat domicile"],
    selectionProcess: "Prelims → Mains → Interview"
  },
  {
    id: "j20",
    title: "HSSC Group-D (MTS / Peon)",
    org: "Haryana Staff Selection Commission",
    sector: "Clerical / Administrative",
    state: "Haryana",
    qualification: "10th Pass",
    vacancies: 4800,
    salary: "₹16,900 – ₹53,500 per month",
    age: "18 – 42 years",
    lastDate: "2025-07-20",
    status: "open",
    type: "State",
    description: "HSSC recruits Group-D staff (MTS, Peon, Daftri) for various Haryana state government offices.",
    link: "https://hssc.gov.in",
    requirements: ["Matriculation Pass", "Haryana domicile", "Physical standards"],
    selectionProcess: "Written Exam → Document Verification"
  },
  {
    id: "j21",
    title: "HPPSC HAS (Himachal Administrative Service)",
    org: "HP Public Service Commission",
    sector: "Civil Services",
    state: "Himachal Pradesh",
    qualification: "Graduation",
    vacancies: 120,
    salary: "₹47,600 – ₹1,51,100 per month",
    age: "21 – 35 years",
    lastDate: "2025-10-01",
    status: "soon",
    type: "State",
    description: "HPPSC recruits officers for HP Administrative Service, HP Police Service and Allied Services.",
    link: "https://hppsc.hp.gov.in",
    requirements: ["Graduation from recognised university", "HP domicile", "Hindi/Sanskrit proficiency"],
    selectionProcess: "Prelims → Mains → Viva Voce"
  },
  {
    id: "j22",
    title: "JPSC Combined Civil Services",
    org: "Jharkhand Public Service Commission",
    sector: "Civil Services",
    state: "Jharkhand",
    qualification: "Graduation",
    vacancies: 342,
    salary: "₹56,100 – ₹1,77,500 per month",
    age: "21 – 35 years",
    lastDate: "2025-08-18",
    status: "open",
    type: "State",
    description: "JPSC combined civil services exam for recruitment to Group-A and Group-B services in Jharkhand.",
    link: "https://jpsc.gov.in",
    requirements: ["Graduation", "Jharkhand domicile (reserved categories)", "Hindi/Urdu literacy"],
    selectionProcess: "Prelims → Mains → Interview"
  },
  {
    id: "j23",
    title: "KAS (Karnataka Administrative Service)",
    org: "Karnataka Public Service Commission",
    sector: "Civil Services",
    state: "Karnataka",
    qualification: "Graduation",
    vacancies: 454,
    salary: "₹53,100 – ₹1,67,800 per month",
    age: "21 – 35 years",
    lastDate: "2025-05-25",
    status: "open",
    type: "State",
    description: "KPSC KAS exam for Group-A, Group-B & Group-C Gazetted posts including Karnataka Administrative Service.",
    link: "https://kpsc.kar.nic.in",
    requirements: ["Graduation", "Kannada language knowledge", "Karnataka domicile for reserved posts"],
    selectionProcess: "Prelims → Mains → Interview"
  },
  {
    id: "j24",
    title: "Kerala PSC LD Clerk",
    org: "Kerala Public Service Commission",
    sector: "Clerical / Administrative",
    state: "Kerala",
    qualification: "12th Pass",
    vacancies: 2140,
    salary: "₹22,200 – ₹48,000 per month",
    age: "18 – 39 years",
    lastDate: "2025-04-18",
    status: "open",
    type: "State",
    description: "Kerala PSC recruits Lower Division Clerks for various government departments on a district-wise basis.",
    link: "https://keralapsc.gov.in",
    requirements: ["12th Pass", "Type writing lower grade", "Malayalam proficiency"],
    selectionProcess: "OMR Exam → Rank List Publication"
  },
  {
    id: "j25",
    title: "Manipur PSC Combined Services",
    org: "Manipur Public Service Commission",
    sector: "Civil Services",
    state: "Manipur",
    qualification: "Graduation",
    vacancies: 96,
    salary: "₹44,900 – ₹1,42,400 per month",
    age: "21 – 38 years",
    lastDate: "2025-09-10",
    status: "soon",
    type: "State",
    description: "Manipur PSC Combined Services exam for Manipur Administrative Service and allied posts.",
    link: "https://manipurpsc.gov.in",
    requirements: ["Graduation", "Manipur domicile", "Knowledge of Meitei/English"],
    selectionProcess: "Prelims → Mains → Viva Voce"
  },
  {
    id: "j26",
    title: "Meghalaya PSC – MCS Officer",
    org: "Meghalaya Public Service Commission",
    sector: "Civil Services",
    state: "Meghalaya",
    qualification: "Graduation",
    vacancies: 88,
    salary: "₹44,900 – ₹1,42,400 per month",
    age: "21 – 32 years",
    lastDate: "2025-10-15",
    status: "soon",
    type: "State",
    description: "MPSC recruits for Meghalaya Civil Service, Meghalaya Police Service and allied posts.",
    link: "https://mpsc.nic.in",
    requirements: ["Graduation", "Meghalaya domicile", "English medium knowledge"],
    selectionProcess: "Prelims → Mains → Personality Test"
  },
  {
    id: "j27",
    title: "Mizoram PSC Combined Services",
    org: "Mizoram Public Service Commission",
    sector: "Civil Services",
    state: "Mizoram",
    qualification: "Graduation",
    vacancies: 76,
    salary: "₹44,900 – ₹1,42,400 per month",
    age: "21 – 35 years",
    lastDate: "2025-11-01",
    status: "soon",
    type: "State",
    description: "Mizoram PSC holds combined services examination for various gazetted posts in the State Government.",
    link: "https://mpsc.mizoram.gov.in",
    requirements: ["Graduation", "Mizo language proficiency", "State domicile"],
    selectionProcess: "Written Exam → Interview"
  },
  {
    id: "j28",
    title: "Nagaland PSC – Combined Services",
    org: "Nagaland Public Service Commission",
    sector: "Civil Services",
    state: "Nagaland",
    qualification: "Graduation",
    vacancies: 64,
    salary: "₹47,600 – ₹1,51,100 per month",
    age: "21 – 35 years",
    lastDate: "2025-10-20",
    status: "soon",
    type: "State",
    description: "NPSC conducts combined civil services exam for NCS, NPS and allied services in Nagaland.",
    link: "https://npsc.nagaland.gov.in",
    requirements: ["Graduation", "Nagaland domicile", "English language proficiency"],
    selectionProcess: "Prelims → Mains → Viva"
  },
  {
    id: "j29",
    title: "Odisha Sub-Inspector of Police",
    org: "Odisha Police Recruitment Board",
    sector: "Police",
    state: "Odisha",
    qualification: "Graduation",
    vacancies: 477,
    salary: "₹35,400 – ₹1,12,400 per month",
    age: "20 – 25 years",
    lastDate: "2025-06-28",
    status: "open",
    type: "State",
    description: "Odisha Police Board recruits Sub-Inspectors for Odisha Police through written examination and physical tests.",
    link: "https://odishapolice.gov.in",
    requirements: ["Graduation", "Physical standards", "Odia domicile"],
    selectionProcess: "Written Test → PET/PMT → Medical"
  },
  {
    id: "j30",
    title: "Punjab Patwari",
    org: "Punjab Revenue Department / PPSC",
    sector: "Revenue / Administration",
    state: "Punjab",
    qualification: "12th Pass",
    vacancies: 1152,
    salary: "₹19,900 – ₹63,200 per month",
    age: "18 – 37 years",
    lastDate: "2025-05-15",
    status: "open",
    type: "State",
    description: "Punjab government recruits Patwaris for land records and revenue management under the Revenue Department.",
    link: "https://ppsc.gov.in",
    requirements: ["12th Pass", "Punjab domicile", "Punjabi language literacy"],
    selectionProcess: "Written Exam → Document Verification"
  },
  {
    id: "j31",
    title: "Sikkim PSC Combined Services",
    org: "Sikkim Public Service Commission",
    sector: "Civil Services",
    state: "Sikkim",
    qualification: "Graduation",
    vacancies: 52,
    salary: "₹44,900 – ₹1,42,400 per month",
    age: "21 – 35 years",
    lastDate: "2025-09-30",
    status: "soon",
    type: "State",
    description: "SPSC recruits for Sikkim State Services including Sikkim Finance Service and Sikkim Administrative Service.",
    link: "https://spsc.sikkim.gov.in",
    requirements: ["Graduation", "Sikkim Subject Certificate", "Nepali/Hindi language"],
    selectionProcess: "Prelims → Mains → Interview"
  },
  {
    id: "j32",
    title: "TNPSC Group-II Services",
    org: "Tamil Nadu Public Service Commission",
    sector: "Civil Services",
    state: "Tamil Nadu",
    qualification: "Graduation",
    vacancies: 1084,
    salary: "₹35,400 – ₹1,12,400 per month",
    age: "21 – 32 years",
    lastDate: "2025-07-05",
    status: "open",
    type: "State",
    description: "TNPSC Group-II exam for Assistant Section Officer, Municipal Commissioner, and other services in Tamil Nadu.",
    link: "https://tnpsc.gov.in",
    requirements: ["Graduation", "Tamil language proficiency", "TN domicile for reserved posts"],
    selectionProcess: "Prelims → Mains → Oral Test (select posts)"
  },
  {
    id: "j33",
    title: "TSPSC Group-I Services",
    org: "Telangana State Public Service Commission",
    sector: "Civil Services",
    state: "Telangana",
    qualification: "Graduation",
    vacancies: 503,
    salary: "₹56,100 – ₹1,77,500 per month",
    age: "18 – 44 years",
    lastDate: "2025-08-25",
    status: "open",
    type: "State",
    description: "TSPSC Group-I exam for Deputy Collector, DSP, District Registrar and other Class-I gazetted posts in Telangana.",
    link: "https://tspsc.gov.in",
    requirements: ["Graduation", "Telugu language knowledge", "TS domicile preferred"],
    selectionProcess: "Prelims → Mains → Interview"
  },
  {
    id: "j34",
    title: "Tripura PSC Judicial Service",
    org: "Tripura Public Service Commission",
    sector: "Legal / Judicial",
    state: "Tripura",
    qualification: "LLB",
    vacancies: 34,
    salary: "₹44,900 – ₹1,42,400 per month",
    age: "23 – 35 years",
    lastDate: "2025-11-15",
    status: "soon",
    type: "State",
    description: "Tripura PSC recruits for Tripura Judicial Service and Tripura Civil Service through competitive examinations.",
    link: "https://tpsc.gov.in",
    requirements: ["LLB / Graduation", "Bar enrollment", "Bengali/Kokborok proficiency"],
    selectionProcess: "Prelims → Mains → Interview"
  },
  {
    id: "j35",
    title: "Uttarakhand UKPSC Lekhpal",
    org: "Uttarakhand Revenue Department",
    sector: "Revenue / Administration",
    state: "Uttarakhand",
    qualification: "12th Pass",
    vacancies: 760,
    salary: "₹21,700 – ₹69,100 per month",
    age: "21 – 42 years",
    lastDate: "2025-06-20",
    status: "open",
    type: "State",
    description: "UKPSC recruits Lekhpals (land record officers) for revenue administration in Uttarakhand.",
    link: "https://ukpsc.net.in",
    requirements: ["12th Pass with Hindi/English", "Uttarakhand domicile", "Computer proficiency"],
    selectionProcess: "Written Exam → Document Verification"
  },
  {
    id: "j36",
    title: "WBPSC Clerkship Examination",
    org: "West Bengal Public Service Commission",
    sector: "Clerical / Administrative",
    state: "West Bengal",
    qualification: "12th Pass",
    vacancies: 5000,
    salary: "₹22,700 – ₹58,500 per month",
    age: "18 – 40 years",
    lastDate: "2025-07-12",
    status: "open",
    type: "State",
    description: "WBPSC recruits Clerks for various departments of the West Bengal state government.",
    link: "https://wbpsc.gov.in",
    requirements: ["12th Pass", "Bengali language literacy", "WB domicile"],
    selectionProcess: "Written Exam → Personality Test"
  },
  {
    id: "j37",
    title: "ANDAMAN PSC Combined Services",
    org: "A&N Islands Public Service Commission",
    sector: "Civil Services",
    state: "Andaman & Nicobar Islands",
    qualification: "Graduation",
    vacancies: 42,
    salary: "₹44,900 – ₹1,42,400 per month",
    age: "21 – 35 years",
    lastDate: "2025-10-30",
    status: "soon",
    type: "State",
    description: "A&N Islands PSC recruits for various Group-A and Group-B gazetted services.",
    link: "https://andaman.gov.in",
    requirements: ["Graduation", "English proficiency", "Domicile certificate"],
    selectionProcess: "Written Exam → Interview"
  },
  {
    id: "j38",
    title: "Chandigarh Administration – MTS",
    org: "Chandigarh Administration",
    sector: "Clerical / Administrative",
    state: "Chandigarh",
    qualification: "10th Pass",
    vacancies: 160,
    salary: "₹18,000 – ₹56,900 per month",
    age: "18 – 27 years",
    lastDate: "2025-05-08",
    status: "open",
    type: "State",
    description: "Chandigarh Administration recruits Multi-Tasking Staff for its various departments.",
    link: "https://chandigarh.gov.in",
    requirements: ["10th Pass", "Hindi/Punjabi/English", "Chandigarh domicile"],
    selectionProcess: "Written Exam → Document Verification"
  },
  {
    id: "j39",
    title: "DSSSB Primary Teacher (TGT)",
    org: "Delhi Subordinate Services Selection Board",
    sector: "Education",
    state: "Delhi",
    qualification: "Graduation + B.Ed",
    vacancies: 1807,
    salary: "₹47,600 – ₹1,51,100 per month",
    age: "21 – 30 years",
    lastDate: "2025-07-30",
    status: "open",
    type: "State",
    description: "DSSSB recruits TGT (Trained Graduate Teachers) for Delhi Government schools across various subjects.",
    link: "https://dsssb.delhi.gov.in",
    requirements: ["Graduation + B.Ed", "CTET/DTET qualification", "Delhi domicile preferred"],
    selectionProcess: "Tier-I CBT → Tier-II CBT → Document Verification"
  },
  {
    id: "j40",
    title: "JKPSC KAS (Kashmir Admin Service)",
    org: "J&K Public Service Commission",
    sector: "Civil Services",
    state: "Jammu & Kashmir",
    qualification: "Graduation",
    vacancies: 187,
    salary: "₹56,100 – ₹1,77,500 per month",
    age: "21 – 37 years",
    lastDate: "2025-09-12",
    status: "soon",
    type: "State",
    description: "JKPSC KAS exam for recruitment to J&K Administrative Service, J&K Police Service and allied posts.",
    link: "https://jkpsc.nic.in",
    requirements: ["Graduation", "J&K domicile certificate", "Urdu/Hindi proficiency"],
    selectionProcess: "Prelims → Mains → Viva Voce"
  },
  {
    id: "j41",
    title: "Ladakh Autonomous Hill Development Council – Jr Engineer",
    org: "LAHDC, Leh",
    sector: "Engineering",
    state: "Ladakh",
    qualification: "Diploma / B.E",
    vacancies: 38,
    salary: "₹35,400 – ₹1,12,400 per month",
    age: "18 – 40 years",
    lastDate: "2025-08-05",
    status: "open",
    type: "State",
    description: "LAHDC Leh recruits Junior Engineers for civil and electrical infrastructure projects in Ladakh UT.",
    link: "https://leh.nic.in",
    requirements: ["Diploma/B.E in Civil or Electrical", "Ladakh domicile", "Hindi/English proficiency"],
    selectionProcess: "Written Test → Interview"
  },
  {
    id: "j42",
    title: "Puducherry PSC – Combined Services",
    org: "Puducherry Public Service Commission",
    sector: "Civil Services",
    state: "Puducherry",
    qualification: "Graduation",
    vacancies: 74,
    salary: "₹44,900 – ₹1,42,400 per month",
    age: "21 – 35 years",
    lastDate: "2025-11-10",
    status: "soon",
    type: "State",
    description: "PPSC recruits for Puducherry Civil Service and allied Group-A services through competitive examination.",
    link: "https://ppsc.py.gov.in",
    requirements: ["Graduation", "Tamil/Telugu/Malayalam/English", "Puducherry domicile"],
    selectionProcess: "Prelims → Mains → Interview"
  }
];

// Merge all jobs
JOBS.push(...EXTRA_JOBS);
